### ISSUE TITLE
Update the style of the About page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#107]
## Background

#105 organizes the styles and themes in this repo. A description of how style and theme files are organized is available in https://github.com/Sage-Bionetworks/challenge-registry/blob/main/docs/app-styles-themes-assets.md.

## Task

- Validate the current organization of the styles and themes via the completion of this task
- Get familiar with how style and theme files are organized
- [ ] Update the style and theme of the About page so it looks "nicer" (currently the page is just a dump of text)

## Tips

1. There difference between SCSS style and theme files are:
    - style: layout
    - theme: color and typography

3. Prefer to use CSS class selectors (e.g. `.challenge-registry-title { ... }`) to modify the style and theme of HTML components instead of defining styling for HTML elements directly (e.g. `h2 { ... }`).

**Comment by tschaffter** [comment]
@rrchai If you want to give a shot to changing the style of a component before I leave, this ticket is the place to start.

**Comment by tschaffter** [comment]
@vpchung Is the About page replaced by the Meet the Team page in the mockups?

**Comment by vpchung** [comment]
There is still an About page; I did not think to create a mockup for it.

**Comment by vpchung** [comment]
![image](https://user-images.githubusercontent.com/9377970/161163170-15b22621-d10e-4094-8c69-d9fa2692d6aa.png)


We can use this as a start, but I think some extra content will be needed, i.e. I mentioned that more information about the MIAC schema can be found in our About Page.  I don't have the thinking power right now to write it currently :satisfied:
