### ISSUE TITLE
Create wireframes for Q2 release

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#109]
By the end of Q2, we want to enable organization to register new Challenges.

- [x] #108 
- [x] #110
- TBD

**Comment by tschaffter** [comment]
@vpchung Just created this ticket in the new repo to get us started with the creation of the new/updated wireframes.

**Comment by vpchung** [comment]
[Link to full design on Figma](https://www.figma.com/file/pHtscIhOFhdd4Poym3fI8T/Challenge-Registry)

@tschaffter @rrchai Some pages have been redesigned to match with the theming/styling I was going for in our [existing landing page](https://test.challenge-registry.org/).  I have two more pages I need to work on (Challenge Details and Newsfeed) - let me know if I should think about other pages as well.

Hopefully, this gives you both enough to work on for the upcoming sprint :innocent:
