### ISSUE TITLE
Design Challenge registration page for Organizations

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#110]

**Comment by vpchung** [comment]
![image](https://user-images.githubusercontent.com/9377970/160277704-4110def5-c402-462d-80ed-e3514dce6be6.png)

This current design will make it so a user will make a request, then we will create the organization account for them. (That way, we can monitor what gets added).  Not sure if we want to approach things this way in the long-run, but I think for now, we can take on this burden.

[Link to full design on Figma](https://www.figma.com/file/pHtscIhOFhdd4Poym3fI8T/Challenge-Registry)
