### ISSUE TITLE
Design page `Meet our Team`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#113]
Example: Kaggle's [Meet our Team page](https://www.kaggle.com/about/team)

**Comment by vpchung** [comment]
![image](https://user-images.githubusercontent.com/9377970/160276610-c6eda13e-38e5-4640-952c-bde601664506.png)

[Link to full design on Figma](https://www.figma.com/file/pHtscIhOFhdd4Poym3fI8T/Challenge-Registry)
