### ISSUE TITLE
Upgrade footer to UI v3 in teleportHQ

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#124]
[Footer design](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry) (Figma)

## Task

- Update the footer component in the library [web-ui](https://github.com/Sage-Bionetworks/challenge-registry/tree/main/libs/web/ui).
- See doc on [how to set update the style and theme of a component](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/docs/app-styles-themes-assets.md).

**Comment by vpchung** [comment]
Footer component has been exported to teleportHQ, collectively with the navbar components.

[Project on teleportHQ](https://play.teleporthq.io/projects/figmaexport-challengeregistry-mockup-navbaruser-dpqc5h)
