### ISSUE TITLE
Explore generation of HTML/SCSS from Figma

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#137]
## Task

- Review existing solutions that can generate HTML and/or SCSS code from a Figma document. For example:
  - https://www.figma.com/community/plugin/742750636238601912/CSSGen
  - https://www.figma.com/community/plugin/843123176259183001
  - [Your first Figma to HTML and CSS Export](https://youtu.be/qVGHz9Hr1bU) (video)
- Document the solutions reviewed.

## Motivation

- Save development time by using automatically generated code.
- Generated code can teach us new things/syntax.

**Comment by vpchung** [comment]
Interesting - I'll take a look sometime next week.

**Comment by vpchung** [comment]
I will be tackling #124 with this exercise.

### [CSSGen](https://www.figma.com/community/plugin/742750636238601912/CSSGen)
**Verdict**: maybe :wavy_dash:
* easy to use, but depends on Color and Text Styles already defined. Before this exercise, I hadn't define any Text Styles - if we decide to use this plugin, I would need to identify and define these styles first.

![Screen Shot 2022-04-07 at 12 31 28 AM](https://user-images.githubusercontent.com/9377970/162144944-6bddefb9-210d-491f-9875-249e5419d863.png)

* last update was Feb 2022; maintainer ([@oriziv](https://www.figma.com/@oriziv)) is responsive to requests and feedback

### [UIKIT to SCSS](https://www.figma.com/community/plugin/843123176259183001/UIKIT-to-SCSS)
**Verdict**: nah :x:
* not intuitive to use
* took about 15 minutes to figure out how to configure accordingly, which imo, wasn't worth the effort, given the end result:

![Screen Shot 2022-04-07 at 12 16 46 AM](https://user-images.githubusercontent.com/9377970/162141962-2208625f-e901-47e3-bc36-934ea0dc1c7c.png)

* [last commit](https://github.com/caffeinalab/figma-uikit-to-scss/commits/master) dated May 2021; may be safe to assume that the plugin is not regularly maintained

### [Export Kit](https://www.figma.com/community/plugin/917838882021857002/Export-Kit---Lightning-Storm)
**Verdict**: nah :x:

* requires a membership and subscription plan - I would register/pay, but based on the Figma Community comments, I am a little hesitant to hand over my information....
* there are [Design rules](https://exportkit.com/kits/export-kit-tutorials/figma-design-rules) that must be followed for the export to work, which may be worth the effort if the end results are good.  But again, some of the community comments are not convincing me that this is a reliable plugin.

### [teleportHQ - Figma to Code](https://www.figma.com/community/plugin/992726161890204477/teleportHQ---Figma-to-Code---Export-HTML%2C-CSS%2C-React-%26-Vue)
**Verdict**: yes :white_check_mark:

* easy to use: designs are first exported to teleportHQ as a new project; from there, you may select to export the project as either Angular, HTML, etc.
     - I tried both Angular and HTML exports, and they export well. Some manual edits and plug-and-chug are required though.

![Screen Shot 2022-04-07 at 1 10 20 AM](https://user-images.githubusercontent.com/9377970/162153438-c9bc53c7-a8a4-48c6-8bcd-b1f963e8c1b6.png)

* regularly maintained; last update was 5 April 2022
* free to use and [open-source](https://github.com/teleporthq/teleport-code-generators)
* only downside (?) is that a login to the teleportHQ is required (despite what the description says)

**Comment by vpchung** [comment]
Tagging @tschaffter and @rrchai to start an async conversation.

**Comment by tschaffter** [comment]
@vpchung [teleportHQ](https://www.figma.com/community/plugin/992726161890204477/teleportHQ---Figma-to-Code---Export-HTML%2C-CSS%2C-React-%26-Vue) looks like a promising solution. Can you give us a demo on Thursday that addresses the following points:

- How the plugin works
- How would you reconcile the use of this plugin with the current approach where layout (aka "style") and color-text (aka "theme") are defined separately and style/theme inheritance is used

**Comment by tschaffter** [comment]
The [minutes of our last team meeting](https://docs.google.com/document/d/1wIUGLVRs--0634fi9IHAPqIzo2IKiTAUfmBPILZX0S8/edit#bookmark=id.rjah16taki6v) describes a protocol proposal for exporting Figma components to our code base.

We discussed with @vpchung that we want to try this protocol first on a simple component like the footer or navbar.

**Comment by vpchung** [comment]
We are moving forward with teleportHQ and have received a license for it.

Closing this ticket now.
