### ISSUE TITLE
[Feature] Display DOI as link

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#1519]
### What projects is this feature for?

OpenChallenges

### Description

As a user, I want to be able to click on the DOI link of a manuscript so that I can access the manuscript in a single click.

### Anything else?

The DOI field has been temporarily removed and need to be added back first.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment]
In addition to adding it back into the app, DOI should also be added to the [data model](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1834177142).
