### ISSUE TITLE
Enable Search Engine Optimization (SEO)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#155]
The goal is to enable Google to understand the content of the pages in the web client. This could be achieved using schema.org and/org JSON-LD. See https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data.

> We will make our application search engine (SEO) friendly and compatible with social media crawlers (for example Facebook or Twitter).

[Source](https://blog.angular-university.io/angular-universal/)

**Comment by rrchai** [comment]
quote from @@tschaffter 
> Let’s take an e-commerce site as an example. This e-commerce site has thousands of clients and thousands of products, and for each product there is a details page.
Because it’s an e-commerce site, it should be server-side rendered (probably using Angular Universal) in order for crawlers to read its content that is needed for SEO.
Source: https://itnext.io/incremental-static-regeneration-for-angular-42b0a8440e53

**Comment by tschaffter** [comment]
Here are a few articles I found but haven't ready (yet).

- https://itnext.io/incremental-static-regeneration-for-angular-42b0a8440e53
  - https://angular.io/guide/universal
    - https://web.dev/rendering-on-the-web/

**Comment by tschaffter** [comment]
Server-side rendering is made possible by [Angular Universal](https://angular.io/guide/universal).

**Comment by tschaffter** [comment]
## Style not fully applied with SSR

- The reason is likely because the font we use is not found on the server.
- It is not possible to inspect the style of an SSR page using the browser developer tools (`element {}`)

### CSR

![image](https://user-images.githubusercontent.com/3056480/181516819-8743b267-9aa9-4351-becd-a9ed6f96dc53.png)

### SSR

![image](https://user-images.githubusercontent.com/3056480/181516893-7578e350-34bf-4cb5-9154-42bce7deb98a.png)

![image](https://user-images.githubusercontent.com/3056480/181516901-9b72be03-9a02-49a9-978f-d04918390a77.png)
