### ISSUE TITLE
Ensure that developer has enough free memory to start the web app

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#158]
Recently Verena and Rong reported an issue where the web app does not start (`nx serve web-app`) because not enough free memory was available. I observed that the dev container uses 2.4 GB of memory after the app has successfully started. During the app startup, the memory used peaked at 2.7 GB.

![image](https://user-images.githubusercontent.com/3056480/163926708-2eb3a1c6-1bdf-4d79-9301-c060ad2240d1.png)

In Rong's case, the dev container didn't have access to 2 GB of memory. Note that the swap provided an additional 1 GB but yet the issue occurred as the total memory of 3 GB was probably not providing a sufficient margin of error. Also swap is much slower than RAM, which makes memory-intensive operations much slower.

![image](https://user-images.githubusercontent.com/3056480/163925645-1205284d-debf-4477-b79d-2c68196829cf.png)

A solution could be to ensure that the dev container has at least 4 GB of memory available. VS Code has an option for this in [devcontainer.json](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/.devcontainer/devcontainer.json). This way, I expect that the dev container will not start if not enough memory is available. Hopefully VS Code will provide a descriptive message for this, thus prompting the developer to close some apps to free memory. This should reduce the risk of bumping into any memory issues during development.

Tagging @vpchung and @rrchai who bumped into this issue

**Comment by rrchai** [comment]
Thanks @tschaffter. 

I tried to add this option,  "hostRequirements" (described [here](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_minimum-host-requirements)) in the `devcontainer.json`:

```json
"hostRequirements": {"memory": "4gb"}
```

With this ^ option, it did ask me if I want to continue building the devcontainer with the memory exceed my docker's memory limit.

<img width="417" alt="Screen Shot 2022-04-18 at 5 49 02 PM" src="https://user-images.githubusercontent.com/73901500/163932877-82c18b73-edad-466f-9c47-1738dd5bcd36.png">

However, after the container was built, the total memory was still same as the docker daemon's memory limit (~2G). 

<img width="538" alt="Screen Shot 2022-04-18 at 11 00 20 PM" src="https://user-images.githubusercontent.com/73901500/163936262-847b9938-4e29-48ef-9d9f-e92f7c5abda9.png">

---
So, alternatively, I increased the memory limit of docker daemon to 4G using Docker Desktop and it worked:

<img width="1045" alt="Screen Shot 2022-04-18 at 11 05 51 PM" src="https://user-images.githubusercontent.com/73901500/163936956-6affb5ca-95cd-49fb-8a03-6e3f53700283.png">
<img width="525" alt="Screen Shot 2022-04-18 at 11 12 42 PM" src="https://user-images.githubusercontent.com/73901500/163937849-5f151901-6afe-4dd2-897b-f9e15dce459a.png">


---
I also tried set docker limit as 6G > devcontainer's "hostRequirements" setting as 4G. The total memory of devcontainer was 6G. It seems the "hostRequirements" either not able to overwrite the docker's limit or I didn't use the right flag.

**Comment by tschaffter** [comment]
@rrchai So the "hostRequirements" is indeed a requirement and not a "configuration" options. The behavior you described makes sense to me. Can you please open a PR that adds the 4 GB of memory requirement to the dev container definition?

**Comment by rrchai** [comment]
@tschaffter oh right, I understand the behavior now.
If the devcontainer's requirement is larger than docker configured memory limit, the memory limit will not be overridden by the requirement. So the requirement only will be used when the docket limit is high (e.g >7G in your case). I guess we also need to change the configuration of docker somewhere?
