### ISSUE TITLE
Track Component Completions

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/challenge-registry#164]
Use this ticket to track the completion progress (whether the component is created), by comparing the "page" components implemented in the current monorepo with all the designed pages in the [figma](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry?node-id=158%3A2962).

```diff
(2/4): completed 2 out of 4
+    : completed
-    : missing
```
---

### All pages:

<details>
<summary>(8/11) Home: </summary>

```diff
+ Landing-host-list
+ Landing-registration
+ Landing-search
+ Landing-challenge-list
+ Landing-sponsor-list
+ Landing-stats-viewer
+ Landing-topics-view
- Landing-add-challenge
- Team
+ About
- Search
```
</details/>

<details>
<summary>(2/2) Search:</summary>

```diff
+ Search Challenge
+ Search Org
```
</details/>

<details>
<summary>(5/7) Challenge:</summary>

```diff
+ Header
+ Overview
- Challenge Details
- Organizers
+ Sponsors
+ Stargazers 
+ Setting
```
</details/>

<details>
<summary>(4/9) User Profile:</summary>

```diff
+ Header
+ Overview
+ Challenges
+ Starred
- Setting-Profile
- Setting-Account
- Setting-Social-Links
- Setting-My-Org
- Setting-Notification
```
</details/>

<details>
<summary>(4/4) Org Profile:</summary>

```diff
+ Overview
+ Challenges
+ Members
+ Setting
```
</details/>

<details>
<summary>(0/2) Add a Challenge/Org:</summary>

```diff
- Add Challenge
- Add Org
```
</details/>

<details>
<summary>(2/4) Login/Register:</summary>

```diff
+ Login
- Forget Password
- Reset Password
+ Register
```
</details/>

<details>
<summary>(1/1) Errors:</summary>

```diff
+ Errors
```
</details/>

<details>
<summary>(0/1) Newsfeed:</summary>

```diff
- Newsfeed
```
</details/>

@tschaffter @vpchung feel free to modify if I miss anything.

**Comment by tschaffter** [comment]
Maybe a more seamless way to track the implementation of the components from Figma to the app is using a spreadsheet. @vpchung @rrchai

**Comment by rrchai** [comment]
@tschaffter Either way works for me. I can start a spreadsheet if needed.

**Comment by tschaffter** [comment]
## TODO

- [ ] Create spreadsheet to track the progress of the creation of the UI components (@rrchai )

**Comment by tschaffter** [comment]
The goal of this ticket is to create a plan for exporting UI components to code. For example, let's assume that a Component A is used in a Component B, then it should make sense to export Component A first, then make use of Component A when exporting Component B.

@vpchung probably has the best understanding of how UI components are organized. If time allows, we can work on this plan together during tomorrow's meeting.

**Comment by tschaffter** [comment]
Replaced by #312
