### ISSUE TITLE
Release devcontainer image 0.3.0

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#183]
## Proposed updates

- Add `htop`
- Add `unzip`
- Add `hadolint` (system + VS Code?)
- ~Add [Git Credential Manager](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git)~

Any other updates/tools you would like to add to the image? @rrchai @vpchung

**Comment by tschaffter** [comment]
@vpchung @rrchai Is there a terminal styling tool that you could recommend, either [Fancy Git](https://github.com/diogocavilha/fancy-git) or another one? I think that I remember seeing Verena using another one that looked less crowded than Fancy Git.

**Comment by rrchai** [comment]
@tschaffter I know [oh-my-bash](https://github.com/ohmybash/oh-my-bash) or [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) is popular. fancy-git looks cool, too.

**Comment by vpchung** [comment]
Oh, I actually stylized the prompt directly in .bashrc..... 😅   Should've known there were tools already.

fancy-git looks nice, as do oh-my-bash.

**Comment by tschaffter** [comment]
## Update

- Adding `unzip`
