### ISSUE TITLE
Document how to export Figma components to code

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#197]
Document how to export Figma components to code.

The article/doc page on how to setup the an EC2 for remote development could be used as an example for the structure. 1) Introduction and motivation, 2) SOP specific to this project but written in a way that it could still be useful to others at Sage.

**Comment by tschaffter** [comment]
@vpchung Can you share a brief update for this ticket and expected completion date (assigned to July sprint)?

**Comment by tschaffter** [comment]
Added to Sprint 22.10

**Comment by tschaffter** [comment]
This is the last items towards completing #659.

**Comment by tschaffter** [comment]
A PR for this task is available for review. Targeting to complete this task this sprint (22.11).

**Comment by vpchung** [comment]
Done.
