### ISSUE TITLE
Fix 10s-ish delay to load web app on EC2+devcontainers

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#209]
@rrchai reported that the web app run in development mode (hot reload) takes about 10 extra seconds to reload the web app in the browser compared to when he is developing locally and without using the devcontainer.

@rrchai Is it the web app dev server that takes about 10 seconds to reload - you can see in the terminal when the reload is done - or is for the browser to refresh once the dev server is done reloading?

Could this be related to the slower download speed of Rong?

Suggestions:
- Try to compare when running the dev server on EC2 without and with devcontainers, and locally with devcontainers.

**Comment by tschaffter** [comment]
@rrchai I propose to increase the priority of this ticket to `High` so that we can solve this issue that affects the quality of your dev environment.

**Comment by tschaffter** [comment]
@rrchai Did your internet speed upgrade solved this issue?

**Comment by rrchai** [comment]
Ah, I forgot to test it yesterday. I am not able. I will get back to you once I am able to login to my JC to start the instance.

**Comment by rrchai** [comment]
@tschaffter I can confirm that the delays are not there any more.

FYI: The issues happened when my downloading speed was around 10 Mbit/s. There is no obvious delay with my current speed at this moment:
```console
Testing download speed................................................................................
Download: 78.77 Mbit/s
```
