### ISSUE TITLE
Blank page when starting the app after recent changes

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/challenge-registry#261]
Pulling from `main` now result in a blank page when starting the app:

![Screen Shot 2022-06-01 at 12 16 38 PM](https://user-images.githubusercontent.com/9377970/171484477-3c186e96-5d6f-4610-957f-55084a379af1.png)

From our technical meeting today, we suspect that it might be due to recent updates to the dev environment.

**Comment by tschaffter** [comment]
I can reproduce the blank page issue when starting the web app with `nx serve web-app`. The API and API DB are running using docker.

**Comment by tschaffter** [comment]
The browser console shows the following errors. This is probably because KC is not up.

```console
ERROR 
Object { error: "Timeout when waiting for 3rd party check iframe message." }
[core.mjs:6500:12](webpack:///node_modules/@angular/core/fesm2020/core.mjs)
Object { error: "Timeout when waiting for 3rd party check iframe message." }
```
