### ISSUE TITLE
Try to deploy EC2 for remote host development with the service catalog

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#289]
The Cnb account is being upgraded to a "production" account. This means:

- all resources must be deployed using CloudFormation / scepter
- no AWS Management Console

@rrchai @vpchung It looks like the Cnb account may not be the best after all. Could you give a try at deploying an EC2 using the service catalog instead? If this approach works, we will update our documentation. Thanks!

**Comment by thomasyu888** [comment]
Well - I used the word "must", but I realize that may be a little strong.  At least it's my understanding from IT that "production level" accounts _should_ have resources created via cloudformation.  There are benefits to doing so, like if resources are accidentally deleted, you can re-run the cloudformation stack.  That said, I'm actually uncertain that cloudformation stacks _MUST BE_ used to be HIPAA compliant?

One option is to add Verena / Rong as members to the DnT dev account, but that said, Brian also has the expectation AWS resources be created via code (aka, cloudformation, terraform, etc etc).  Ultimately, I think we should have a discussion about how best to approach the development of AWS infrastructure for our projects and get a better understanding of what IT expects of us with each of the accounts.  We can certainly set our own expectations and have IT approve of them?

**Comment by vpchung** [comment]
@tschaffter would this mean we should terminate the current EC2? Or should we pause for now?
