### ISSUE TITLE
Add footer to shared library

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#326]

**Comment by vpchung** [comment]
@tschaffter can you provide more context for this one?  Do you want me to add the footer component from `challenge-registry/ui` to `shared/web-components/src/lib`?

**Comment by tschaffter** [comment]
The idea is to move the footer component to a new library in `shared/` and the user it in two or more apps for the sake of demonstrating reusable UI projects. Following [Nx library type convention](https://nx.dev/structure/library-types), we could create a library named `shared/ui` or `shared/ui-footer` (more specific). I would go for the former option to minimize the number of projects, and go for the second option only if needed in the future. To create `shared/ui`, you could copy the folder `challenge-registry/ui`, remove everything but the footer, rename names and paths in `project.json`, and add an entry for this new library in `workspace.json`.

**Comment by tschaffter** [comment]
@vpchung Blocking this issue until #411 is complete: 1) the implementation of the User Profile page will clarify how to organize the styles and themes for project-specific libraries, then 2) identify and document how to convert component to/create shared components (this ticket).

**Comment by tschaffter** [comment]
We decided that we will move component to shared library when they need to be shared by multiple projects. This condition is not met for the footer.
