### ISSUE TITLE
Add "Meet the Team" page component

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/challenge-registry#355]

**Comment by tschaffter** [comment]
Is the page designed to be fed by an array of user objects? I can see us adding more members to the team, starting with Jake and Aerilynn (intern).

**Comment by tschaffter** [comment]
@vpchung Can you share a brief update for this ticket and expected completion date (assigned to June(-July) sprint)?

**Comment by vpchung** [comment]
@tschaffter sorry for the delay.  I will finish it this sprint.

**Comment by tschaffter** [comment]
Added to Sprint 22.09

**Comment by tschaffter** [comment]
TODO: Add the scope of this task.

**Comment by tschaffter** [comment]
Added to Sprint 22.10
