### ISSUE TITLE
Define css properties category for colors and typography

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/challenge-registry#362]
Since we will re-organize the css properties related to colors and typography to `*-theme.scss` file. I think it is helpful for us to list out all css properties that belongs to these two categories.

colors (simply any properties contain "color"), some most frequently used examples:
- color
- background-color
- border-color
- border-[top/bottom/left/right]-color

typography (https://www.w3schools.com/cssref/pr_font_font.asp):
- font-style
- font-variant
- font-weight
- font-size
- font-family
- line-height

--- 
- [ ] team add more if missing any
- [ ] add to [app-styles-themes-assets.md](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/docs/app-styles-themes-assets.md)

**Comment by tschaffter** [comment]
That's a great idea! What about creating a doc page in `docs/` to keep track of this information?

**Comment by tschaffter** [comment]
The sets of properties look good to me. BTW we should probably group theme constants in a file similar to [_constants.scss](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/libs/challenge-registry/styles/src/lib/_constants.scss) from the library `challenge-registry/styles`.

**Comment by rrchai** [comment]
> we should probably group theme constants in a file similar to [_constants.scss](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/libs/challenge-registry/styles/src/lib/_constants.scss) from the library challenge-registry/styles.

Agree! Should we ideally place our [_palette.scss](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/apps/challenge-registry/src/_palette.scss) to the same location as [_constants.scss](https://github.com/Sage-Bionetworks/challenge-registry/blob/main/libs/challenge-registry/styles/src/lib/_constants.scss)'s?

**Comment by tschaffter** [comment]
That seems a good idea.

**Comment by tschaffter** [comment]
@rrchai Is this PR already addressed by #434?

**Comment by rrchai** [comment]
@tschaffter not yet, but I can add it to the `figma-to-code.md`
