### ISSUE TITLE
Export User Profile page to teleportHQ

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#409]
- Target date: July 22, 2022 (along with #411 )
- Extended target dateline: July 29, 2022

**Comment by tschaffter** [comment]
@vpchung Do you plan to export the page at once or component by component? The later may contribute to make PRs smaller and easier to review.

**Comment by vpchung** [comment]
I exported all of the pages as a single app and was going to dump them into the project for @rrchai once I finished configuring them in teleportHQ.

**Comment by tschaffter** [comment]
Back to contributing to the web app after a few weeks in the Underworld (aka backend)! Got the user profile page up and running (`nx serve challenge-registry`). Can't wait to see the page after your makeover @vpchung @rrchai !

![image](https://user-images.githubusercontent.com/3056480/178888173-7521fac3-94c4-437f-bbbe-cdbbbfeaa89e.png)

**Comment by rrchai** [comment]
@vpchung Thanks for exporting the pages. I see you are configuring the entire project. If it will take a lot of your time, you could dump raw styling files to me with an example how to configure on a single page. I might be able to help on the configuration on other pages. Feel free to export page by page if this is easier than exporting entire project.

**Comment by vpchung** [comment]
@rrchai many, many, MANY apologies for the delay!!! Finally had time to configure and export the pages out to the web app.  All of the raw HTML and SCSS can be found under `/libs/challenge-registry/user-profile`.

In addition to the pages, I also configured some parts of the template into components, including:
- basic-stats
- challenge-card
- organization-card

These can be found under `/libs/challenge-registry/user-profile/components`.

**Comment by tschaffter** [comment]
Extended target deadline is now July 29, 2022.

**Comment by tschaffter** [comment]
The export TO teleportHQ is actually done. :)
