### ISSUE TITLE
Document workflow for exporting Figma assets (e.g. svg images)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#467]
Rong requested access to the icons used in the Figma mockup UI v3 in #434. These icons should ideally be in SVG format to reduce the app bundle size and page loading time. Svg icon can also be scaled to any size without any loss of quality.

1. Identify how to export assets like icons from Figma.
2. Add icons requested by Rong to the codebase.
3. Document the process of exporting assets from Figma to code.

**Comment by vpchung** [comment]
All icons I used in the mockups are from [Material](https://developers.google.com/fonts/docs/material_icons).  For any icons that can't be found and/or replaced by Material, we could use this [plug-in](https://www.figma.com/community/plugin/814345141907543603/SVG-Export) to export as SVG.
