### ISSUE TITLE
User Profile Page: Make the page content fit below the navbar

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/challenge-registry#533]
The width of page container is not matched with the navbar, which uses 100% width. Since the other components of this page exported by teleportHQ might be related with the total width, changing width of the page container to 100% width only is not enough.

<img width="1154" alt="Screen Shot 2022-08-12 at 13 07 47" src="https://user-images.githubusercontent.com/73901500/184408980-cbaa6bea-1c52-42a3-b18d-7a32f81de6f0.png">

**Comment by tschaffter** [comment]
The profile page is now no longer than the navbar thanks to @rrchai .

![image](https://user-images.githubusercontent.com/3056480/187511491-bedda750-e7eb-4c0f-a10f-48ce4450b43f.png)

Other fixes and improvement to the layout will be made in separate ticket, including centering the page content.

**Comment by tschaffter** [comment]
@rrchai Can you please add a description of the current and expected/target behavior?
