### ISSUE TITLE
Explore `pnpm` and `yarn v3`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#588]
Yarn v1 is in maintenance mode since 2020. `yarn v3` and `pnpm` are the most promising candidates to replace `yarn v1`. They should also provide a solution to the need (?) to remove `node_modules` after a git merge.

> **Node**
> Yarn v1 is still extensively used because v2 introduced many broken changes, which lead to a controversy. Not sure about the state of v3.

**Comment by tschaffter** [comment]
[This article](https://www.linkedin.com/pulse/yarn-3-vs-npm-8-dev-teams-2022-alex-alksne/?trk=articles_directory) (2022-01) says that import features like go-to-definition are missing from yarn v3.

**Comment by tschaffter** [comment]
- [Angular is still using yarn v1.](https://github.com/angular/angular-cli/issues/16980)
- [Nx is still using yarn v1](https://github.com/nrwl/nx/issues/2386)

**Comment by tschaffter** [comment]
## Upgrading to yarn berry (v3)

I upgraded to yarn v3 using the instruction in [this article](https://medium.com/inato/make-your-ci-faster-and-improve-developer-experience-upgrade-to-yarn-2-with-or-without-939524d9bef2) and was able to successfully build and run the challenge registry after clearing the nx cache.

**Comment by tschaffter** [comment]
## Benchmark

## Yarn 1

Install:

```console

```

Install with lock file:

```console

```

## Yarn 3

Install:

```console
$ hyperfine --runs 5 'rm -fr node_modules && rm -fr yarn.lock && yarn install'
Benchmark 1: rm -fr node_modules && rm -fr yarn.lock && yarn install
  Time (mean ± σ):     52.966 s ±  1.156 s    [User: 66.253 s, System: 33.588 s]
  Range (min … max):   51.778 s … 54.747 s    5 runs
```

Install with lock file:

```console
$ hyperfine --warmup 1 --runs 5 'rm -fr node_modules && yarn install --immutable'
Benchmark 1: rm -fr node_modules && yarn install --immutable
  Time (mean ± σ):     38.957 s ±  5.146 s    [User: 47.455 s, System: 34.421 s]
  Range (min … max):   35.419 s … 47.780 s    5 runs
```

**Comment by tschaffter** [comment]
## Switching between Yarn versions

```console
vscode@ade7130aff68:/workspaces/challenge-registry$ yarn set version 1.22.17
➤ YN0000: Retrieving https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn-1.22.17.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.17.cjs
➤ YN0000: Done in 1s 330ms
vscode@ade7130aff68:/workspaces/challenge-registry$ yarn set version 1.22.19
Resolving 1.22.19 to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-1.22.19.js...
Saving it into /workspaces/challenge-registry/.yarn/releases/yarn-1.22.19.cjs...
Updating /workspaces/challenge-registry/.yarnrc...
Done!
vscode@ade7130aff68:/workspaces/challenge-registry$ yarn set version 3.2.2  
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.2.cjs
➤ YN0000: Done in 0s 490ms
```

**Comment by tschaffter** [comment]
## Install project dependencies with PnP

- Comment out the line `nodeLinker: node-modules` in `.yarnrc.yml`.
- `yarn install` generates the following error:

```console
# This file contains the result of Yarn building a package (challenge@workspace:.)
# Script name: postinstall

Error: EROFS: read-only filesystem, open '/node_modules/.ngcc_lock_file'
    at makeError$1 (/workspaces/challenge-registry/.pnp.cjs:33270:24)
    at EROFS (/workspaces/challenge-registry/.pnp.cjs:33297:10)
    at ZipFS.prepareWriteFile (/workspaces/challenge-registry/.pnp.cjs:35131:13)
    at ZipFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:35115:53)
    at /workspaces/challenge-registry/.pnp.cjs:36197:20
    at /workspaces/challenge-registry/.pnp.cjs:36413:60
    at ZipOpenFS.getZipSync (/workspaces/challenge-registry/.pnp.cjs:36542:14)
    at ZipOpenFS.makeCallSync (/workspaces/challenge-registry/.pnp.cjs:36413:17)
    at ZipOpenFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:36194:17)
    at VirtualFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:35527:24)
```

Related:

- https://dev.to/arcanis/introducing-yarn-2-4eh1
- [Nx does not support PnP yet.](https://github.com/nrwl/nx/issues/2386)
- [Storybook does not support PnP yet.](https://github.com/storybookjs/storybook/issues/18626)

Using Yarn 2+ without PnP already provides a significant boost in performance and probably Yarn bug fixes. Further exploration of PnP will be left for another day/task.

**Comment by pongells** [comment]
Hi @tschaffter, I am a bit confused by the lack of official documentation -- does the result of this exploration mean nx supports yarn3 (with node-modules) without issues?

**Comment by ld210** [comment]
Yarn PnP mode (zero install) brought a significant boost in performance in our CI. 15 to 20mn before, 5 to 8mn with PnP, which is a huge improvement. A good chunk of those 5 to 8 minutes is taken by pods waiting to be ready, so even if the code base continues to grows, CI time will not grow as fast. It's a huge incentive towards PnP, and i don't see myself rollback to old node_modules, my teammates would lose their mind.

**Comment by tschaffter** [comment]
@ld210 I need to read more about zero install. While zero install is recommended and used by the Yarn team, it is usually [not recommended to track binary and/or large files on Git(Hub)](https://youtu.be/RcqLV1lU408) such as the `.zip` files that comes with zero install.

I just gave another try to PnP by removing `nodeLinker: node-modules` and now am able to run `yarn install` for this monorepo. With PnP, I can execute binary that live in `node_modules/bin` directly, e.g. `nx`, `serverless`, etc. When using PnP, it seems that I have to prefix these command with `yarn` for them to work, e.g. `yarn nx`, `yarn serverless`. I find it slightly painful to prefix the commands. Is there a workaround?

**Comment by tschaffter** [comment]
Interesting discussion related to my previous comment: https://github.com/yarnpkg/berry/issues/180

**Comment by tschaffter** [comment]
VS Code extensions breaks if they don't find binaries in the path, e.g. `prettier` in the screenshot below:
﻿
<img width="1552" alt="Screen Shot 2022-10-03 at 1 05 02 PM" src="https://user-images.githubusercontent.com/3056480/193669146-fe22a558-abfe-4f7c-aedf-422be63bc1f1.png">

**Comment by tschaffter** [comment]
As mentioned in the first ticket I opened about migrating to Yarn 2+ with PnP, some package may break if they don't specify their dependencies properly. I just bumped into this issue with `Nx` not specifying that it depends on `dotenv`. This issue has been previously reported [here](https://github.com/nrwl/nx/issues/8332).

I can installed `dotenv` manually but it should be removed next time I'm updating Nx, which should solve the above issue.

**Comment by ld210** [comment]
@tschaffter 
the .zip files generated by yarn install are pretty small files. On our project, dependencies went from 2Go to 300Mo, each zip files are relatively small (lots of 10/50ko, biggest one is 7Mo). Some of our tracked assets files are bigger than that, so it is not an issue for us, but it could be for projects with large dependencies.
About the "yarn" prefix, it is indeed annoying ! I didn't found a workaround, but considering the gains, i can live with it.
I found that with PnP, there is a fairly large amount of configuration at the beginning, specific to each project, that can be painful. On our own project, it was relatively easy to make it work. Not having many dependencies, and zero non-Ivy Angular libraries, helped a lot.
You are right, the path to the binaries may change, at each upgrade.
Thanks for the link to the discussion, very interesting, indeed !
All in all, PnP mode in its current state may not be for everyone, it is very project-specific. But the gains can be huge and worth the trouble. Node modules are such a pain, it's a relief not to have to deal with them anymore.
The time saved on CI alone was worth it.
