### ISSUE TITLE
⛰ Evaluate Figma-to-code development workflow

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#659]
The objective is to evaluate means of exporting UI mockups in Figma to code in order to accelerate the development of the Challenge Registry and standardize UI-related processed. This Epic is complete once the Figma-to-code development workflow is documented (SPOs, pros/cons/limitation, etc.)

- [x] #124
- [x] #127
- [x] #137 
- [x] #151
- [x] #197
- [x] #393
- [x] #467
- [x] #468
- [x] #528

**Comment by tschaffter** [comment]
The tentative completion sprint for this Epic is 22.10.

**Comment by tschaffter** [comment]
Verena has opened a PR. Rong and I will try to review it before the end of this sprint (22.11).

**Comment by vpchung** [comment]
Done.
