### ISSUE TITLE
Document Title does not update as expected

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/challenge-registry#708]
### Bug
I noticed as I go through the various pages of the app, the Document Title (observed in the tab) does not update, with the exception of the About page:

![bug](https://user-images.githubusercontent.com/9377970/190511875-f9e7e78b-844d-411b-93a9-27ba60362771.gif)

### Expected behavior
The Document Title will update according to which page the user is on.  For example:

* Home page => `Challenge Registry`
* About page => `About - Challenge Registry` 
* Search page => `Search - Challenge Registry`
* User profile page => ` <first name> <last name> - <username>` (or some other pattern)

Alternatively: not even update the Document Title at all (therefore, removing the title update from the About page).

**Comment by vpchung** [comment]
For better viewing:
![bug](https://user-images.githubusercontent.com/9377970/190512547-7b9dbaca-7999-427b-a921-abdde8bf9a7b.gif)

**Comment by tschaffter** [comment]
This bug should be addressed by #560. The task is loosely related to search engine optimization (SEO).

**Comment by vpchung** [comment]
Gotcha - sorry for the redundant ticket.  I only checked the tickets labeled with `bug`.

**Comment by tschaffter** [comment]
This ticket and description of the expected behavior is useful! This ticket is not referenced in #560 so we can retrieve it easily.
