### ISSUE TITLE
Share Challenge Registry UI Mockup with Sagers

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#723]
The goal is to invite Sagers to review the [Challenge Registry UI Mockup](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry?node-id=0%3A1) v3 and ask them for feedback. The feedback received could then be integrated in v4 of the mockup.

## Timeline

- We are ready to share the mockup and collect feedback.
- It would be nice to share the feedback received during the presentation the team will give mid-October.

## Tasks

- [x] Send out an email to Sage to share the mockup and ask for feedback (Thomas)
- [ ] Review the feedback (Verena)

@vpchung 

- How does this plan sound? Would you have time to review the feedback by mid-October if we asked Sagers to submit it by October 3? The tentative date for the presentation is Oct. 13-14.
- How would you like to receive the feedback?

**Comment by tschaffter** [comment]
Tentatively added to Sprint 22.10

**Comment by vpchung** [comment]
@tschaffter sounds good.  I like collecting feedback directly in the Figma comments, but can understand if people would rather use different means.

**Comment by tschaffter** [comment]
Message shared with Team Sage on Slack:

> The Challenge Registry team needs you! We would like to hear your feedback on the [Challenge Registry UI mockup](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry?node-id=0%3A1). The goal of this project is to build a hub for the participants and organizers of biomedical challenges independently of the platform used to organize the challenges (Synapse, CodaLab, EvalAI, Kaggle, etc.). We are also looking forward to enabling organizers to showcase the challenges they have helped organize on their profile page. Feedback is welcomed anytime but we are grateful if you can submit it by October 3rd. You can make comments directly in Figma or [start a discussion in GitHub](https://github.com/Sage-Bionetworks/challenge-registry/discussions). - On behalf of the Challenge Registry Team: [@Thomas Schaffter](https://sagebionetworks.slack.com/team/UFZ9A076Z), [@verena](https://sagebionetworks.slack.com/team/UMEPTFJ4X),[@Rong](https://sagebionetworks.slack.com/team/U01DV4J0J4B), [@Amy Heiser](https://sagebionetworks.slack.com/team/U03PUVBV55K), [@Jake Albrecht](https://sagebionetworks.slack.com/team/U029ZKX09GV)

**Comment by tschaffter** [comment]
@vpchung Let's add brief summary of the feedback received and close this ticket.

**Comment by tschaffter** [comment]
The comments that we have received can easily be retrieved from Figma.
