### ISSUE TITLE
Explore Yarn PnP - Take 2

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#755]
I recently upgraded this monorepo to Yarn 2+, which greatly reduces the time required to install/update npm dependencies. One issue left unaddressed is the activation of the PnP mode generated an error. See https://github.com/Sage-Bionetworks/challenge-registry/issues/588#issuecomment-1225835942. Using PnP should further reduce the runtime of Yarn locally and in CI/CD workflows.

## Checklist

- ❌ Can add binaries to the path, for example to use `nx` instead of `yarn nx`.
- ❌ Jest works with PnP
- ❔ All VS Code extensions that relies on npm packages work.
- ✔️ Can run `npm install` and `npm install --immutable`.
- ✔️ Accessing package type definition in VS Code
- ✔️ CI/CD workflow can still cache the npm dependencies.

## References

- [Advanced package manager features for npm, Yarn, and pnpm](https://blog.logrocket.com/advanced-package-manager-features-npm-yarn-pnpm/)
- [Getting started with Yarn 2 and TypeScript](https://medium.com/swlh/getting-started-with-yarn-2-and-typescript-43321a3acdee)
  - See relation between `pnpify` and Yarn SDK for VS Code.

**Comment by tschaffter** [comment]
- Clean the yarn cache: `yarn cache clean`
- Cache location:
  - By default: `.yarn/.cache`
  - With `enableGlobalCache: true`: `~/.yarn/berry/cache`

**Comment by tschaffter** [comment]
VS Code extensions breaks if they don't find binaries in the path, e.g. `prettier` in the screenshot below:
﻿
<img width="1552" alt="Screen Shot 2022-10-03 at 1 05 02 PM" src="https://user-images.githubusercontent.com/3056480/193669146-fe22a558-abfe-4f7c-aedf-422be63bc1f1.png">

**Comment by tschaffter** [comment]
As mentioned in the first ticket I opened about migrating to Yarn 2+ with PnP, some package may break if they don't specify their dependencies properly. I just bumped into this issue with `Nx` not specifying that it depends on `dotenv`. This issue has been previously reported [here](https://github.com/nrwl/nx/issues/8332).

I can installed `dotenv` manually but it should be removed next time I'm updating Nx, which should solve the above issue.

**Comment by tschaffter** [comment]
## Jest is broken when using PnP

Multiple tests are failing with the same error:

```console
    ✖  nx run challenge-registry-org-search:test
 FAIL   web-org-search  libs/challenge-registry/org-search/src/lib/org-search.component.spec.ts
  ● Test suite failed to run
       
           TypeError: Cannot read properties of undefined (reading 'resolvedFileName')
       
             at module.exports (../../../../../home/vscode/.yarn/berry/cache/@nrwl-jest-npm-14.5.4-571814ec0a-8.zip/packages/jest/plugins/resolver.ts:85:22)
```

**Comment by tschaffter** [comment]
## Can no longer run `yarn install --immutable` but I could an hour ago

```console
Error: EROFS: read-only filesystem, open '/node_modules/.ngcc_lock_file'
    at makeError$1 (/workspaces/challenge-registry/.pnp.cjs:36734:24)
    at EROFS (/workspaces/challenge-registry/.pnp.cjs:36761:10)
    at ZipFS.prepareWriteFile (/workspaces/challenge-registry/.pnp.cjs:38595:13)
    at ZipFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:38579:53)
    at /workspaces/challenge-registry/.pnp.cjs:39661:20
    at /workspaces/challenge-registry/.pnp.cjs:39877:60
    at ZipOpenFS.getZipSync (/workspaces/challenge-registry/.pnp.cjs:40006:14)
    at ZipOpenFS.makeCallSync (/workspaces/challenge-registry/.pnp.cjs:39877:17)
    at ZipOpenFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:39658:17)
    at VirtualFS.writeFileSync (/workspaces/challenge-registry/.pnp.cjs:38991:24)
```

**Comment by tschaffter** [comment]
## Install Yarn SDK for VS Code

```console
arn dlx @yarnpkg/sdks vscode
```

This scans `package.json` for supported technologies. In the context of this project, it's ESLint, Prettier and TypeScript.

**Comment by tschaffter** [comment]
## Issue related to `/node_modules/.ngcc_lock_file`

Sometimes `yarn install` or `yarn add ...` fail.

```console
$ yarn add -D jest-pnp-resolver
...
➤ YN0002: │ challenge@workspace:. doesn't provide styled-components (pd8d31), requested by redoc
➤ YN0002: │ challenge@workspace:. doesn't provide unzipper (p32a3b), requested by @nxrocks/nx-spring-boot
➤ YN0002: │ challenge@workspace:. doesn't provide xmlbuilder2 (p9250a), requested by @nxrocks/nx-spring-boot
➤ YN0002: │ challenge@workspace:. doesn't provide xpath (paae6e), requested by @nxrocks/nx-spring-boot
➤ YN0002: │ jest-preset-angular@npm:11.1.2 [c9049] doesn't provide jest (p9a8ff), requested by ts-jest
➤ YN0002: │ jest-preset-angular@npm:11.1.2 [c9049] doesn't provide typescript (pc596a), requested by ts-jest
➤ YN0002: │ redoc-cli@npm:0.13.20 doesn't provide core-js (p6cfa3), requested by redoc
➤ YN0002: │ redoc-cli@npm:0.13.20 doesn't provide react-is (pb4ff6), requested by styled-components
➤ YN0002: │ redoc@npm:2.0.0 [0682b] doesn't provide webpack (p1f851), requested by style-loader
➤ YN0002: │ redoc@npm:2.0.0 [c9049] doesn't provide webpack (pe2104), requested by style-loader
➤ YN0002: │ redoc@npm:2.0.0-rc.77 [98264] doesn't provide webpack (p9d479), requested by style-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 898ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 861ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ challenge@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ challenge@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b154d8ad/build.log)
➤ YN0000: └ Completed in 2s 537ms
➤ YN0000: Failed with errors in 5s 599ms
```

**Comment by tschaffter** [comment]
## ❌ Accessing package type definition in VS Code

Consider `import { Component } from '@angular/core';`. I cannot access the type definition, neither via the tooltip or by clicking on open the definition file. Note that I have previously installed the Yarn SDK for VS Code.

![image](https://user-images.githubusercontent.com/3056480/193855671-7c7f0474-c89f-4662-a465-4464eb09d2f6.png)

![image](https://user-images.githubusercontent.com/3056480/193855391-2da19d83-a9cc-4cc4-9840-9e9f84b1e04b.png)

**Comment by tschaffter** [comment]
## Conclusions

I'm timeboxing the exploration of PnP to one day. The short answer is that our project can not use it yet mainly because there is still a lack of support from tools like VS Code, Nx, Jest, etc. PnP requires npm packages to be thorough when defining their dependencies. I could probably resolve these dependency issues if I had time. Instead, I'll wait 1-2 months before trying again.

### Protocol

Here is what I did to enable PnP and try to get it to work with this workspace:

- Remove `node_modules`.
- Comment out `nodeLinker: node-modules` in `.yarnrc.yml`.
- Run `yarn install --immutable`.
- Unplug Ng compiler CLI to solve one of the issue: `yarn unplug @angular/compiler-cli`.
- Install Yarn SDK for VS Code: `yarn dlx @yarnpkg/sdks vscode`

Unfortunately, running tests with Jest are now failing.

### Other considerations

- Using PnP would speedup yarn commands - locally and in CI/CD workflow - as dependencies are stored in memory and the bulky `node_modules` is no longer around.
- PnP has a feature called "zero-install" that consists in storing npm packages as zip archives. The recommendation by the Yarn team is to push these zip archives to Git(Hub). However, GH is not designed to track binary and/or large files. Even if most of the zip archives are small and do not exceed a total of a few hundreds MBs, I'm concerned about the long term decrease of performance of `git` as npm packages are added/removed/updated and past commits slow down `git`. This is especially true in the context of a monorepo that may handle a large number of dependencies.
- Without PnP, it is easy to add `node_modules/.bin` to the path and simply run commands such as `nx`, `serverless`, etc. This approach is no longer possible with PnP.

**Comment by hakimio** [comment]
@tschaffter have you tried `PnPify` to work-around some of the issues like the jest issue?

**Comment by tschaffter** [comment]
@hakimio I tried `yarn pnpify --sdk vscode` at some point, then switch `yarn dlx @yarnpkg/sdks vscode` to as recommended [here](https://javascript.plainenglish.io/getting-started-with-yarn-3-and-typescript-125e7b537e6c).

> Before you could simply yarn pnpify --sdk vscode (I think that was the old command?), however, with Yarn 3, you’ll need to use @yarnpkg/sdks in order to add needed support. This time you have two options, executable or dependency-based SDK support.

What is your experience using `pnpify`?

**Comment by hakimio** [comment]
The linked article talks about adding yarn pnp support to VS Code. I was referring to the issue you had with `jest` where it couldn't find external libraries (`Cannot find module '@angular/common/http' or its corresponding type declarations`). My idea is that it can't find them since it's trying to access `node_modules` directly and if you run `yarn pnpify jest`, `pnpify` would act as a proxy and allow `jest` find the modules.
Personally I don't have much experience with `pnpify`. It's just an idea which might be worth a try.

**Comment by arcanis** [comment]
> ❌ Jest works with PnP.

That seems strange - Jest has supported PnP for a while now, both codebases have tests to enforce it 🤔

**Comment by tschaffter** [comment]
@arcanis Thanks for the info. There are still issues related to Nx-Jest according to this [comment](https://github.com/nrwl/nx/issues/2386#issuecomment-1328095863).
