### ISSUE TITLE
Fix unspecified Python dependencies in README

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#86]
@vpchung reported the following issue:

Might I suggest some additional content to the README? I don’t know if maybe my case is just special and [@Rong (he/him)](https://sagebionetworks.slack.com/team/U01DV4J0J4B) did not experience the same errors as me, but following “Running with Docker” verbatim was met with some errors, e.g. challenge-registry-prepare requires Python 3.9 (never mentioned so our users wouldn’t know) and pipenv already installed (not mentioned until the “Development” section).
We can provide a “shortcut” to users with:

```console
conda create -n rocc nodejs python=3.9
conda activate rocc
conda install -c conda-forge yarn
pip install pipenv
```

**Comment by tschaffter** [comment]
@vpchung I switched to `pipenv` recently to manage the Python virtualenv for the REST API. I find `pipenv` to be much easier to setup and use than conda, especially when it comes to managing virtualenvs in Docker containers.

**Comment by vpchung** [comment]
`pipenv` sounds good to me; my understanding is that Sage is slowly moving towards `pipenv` as the package manager anyway.  So as long as it's mentioned earlier, that should be good!
