### ISSUE TITLE
Identify point of contact for each organization

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#873]
This information is critical so that we can start soon to contact challenge organizations before the release of the closed beta. The goal is to advertise the challenge registry and onboard them so that their data are available in the registry at the time of the release of the closed beta in 2023 Q1.

The contact information could be added to the Google Sheet [Challenge Registry: Data Source](https://docs.google.com/spreadsheets/d/1qq7bohgYq3t_bKTRUVhGsmaYhfuQLWT8ZxUGXTuFXL8).

**Comment by vpchung** [comment]
I spoke with @chepyle and he will identify the point-of-contacts.

**Comment by tschaffter** [comment]
We should have enough points of contact to collect a decent amount of challenge data for the private preview in March.
